management:
    endpoints:
        web:
            exposure:
                include: '*'


spring:
    h2:
        console:
            enabled: true
            path: /h2
    datasource:
        url: jdbc:h2:file:~/data
        username: sa
        password:
        driverClassName: org.h2.Driver
        initialization-mode: always
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
        show-sql: true


server:
    tomcat:
        mbeanregistry:
            enabled: true

